wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_000.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_001.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_002.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_003.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_004.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_005.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_006.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_007.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_008.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_009.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_010.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_011.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_012.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_013.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_014.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_015.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_016.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_017.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_018.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_019.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_020.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_021.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_022.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_023.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_024.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_025.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_026.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_027.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_028.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_029.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_030.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_031.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_032.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_033.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_034.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_035.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_036.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_037.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_038.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_039.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_040.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_041.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_042.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_043.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_044.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_045.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_046.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_047.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_048.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_049.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_050.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_051.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_052.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_053.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_054.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_055.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_056.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_057.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_058.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_059.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_060.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_061.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_062.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_063.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_064.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_065.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_066.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_067.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_068.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_069.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_070.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_071.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_072.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_073.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_074.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_075.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_076.nc
wget https://climexp.knmi.nl/CMIP5/monthly/pr/pr_Amon_ens_rcp85_077.nc

